# This workflow is largely based on
# https://github.com/buschtoens/ember-link/blob/master/.github/workflows/ci.yml
# https://github.com/salsify/ember-css-modules/blob/master/.github/workflows/ci.yml

name: CI

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main

  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: "0 6 * * 0"

env:
  CI: true

jobs:
  Test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: NullVoxPopuli/action-setup-pnpm@v2
      - name: Lint JS
        run: pnpm lint:js
      - name: Lint Handlebars
        run: pnpm lint:hbs
      - name: Browser Tests
        run: pnpm test
      - name: Smoke test production build
        run: node node_modules/puppeteer/install.js && pnpm smoke
      - name: Deploy to staging and test deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEBUG: true
          VOLTA_FEATURE_PNPM: 1
        run: pnpm staging:deploy
      - run: git log --pretty=%h -n1 > dist/REVISION.txt
      - name: Upload Build for next job
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: prod-build
          path: dist

  Deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: Test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install Node
        uses: volta-cli/action@v4
      - name: Install netlify-cli
        run: npm install -g netlify-cli
      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: prod-build
          path: dist
      - name: Deploy site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          VOLTA_FEATURE_PNPM: 1
        run: netlify deploy --dir=dist --prod --message "Revision $(cat dist/REVISION.txt)"
